### ISSUE TITLE
拉取镜像失败

### ISSUE THREAD

**Issue by ysicing** [goodrain/rainbond-install#24]
```
          ID: runner-pull
    Function: cmd.run
        Name: docker pull rainbond/runner; docker tag rainbond/runner goodrain.me/runner;docker push goodrain.me/runner
      Result: False
     Comment: Command "docker pull rainbond/runner; docker tag rainbond/runner goodrain.me/runner;docker push goodrain.me/runner" run
     Started: 22:21:03.276421
    Duration: 211625.232 ms
     Changes:
              ----------
              pid:
                  26290
              retcode:
                  1
              stderr:
                  Put http://goodrain.me/v1/repositories/runner/: dial tcp 172.30.42.1:80: getsockopt: connection refused
```
