### ISSUE TITLE
update pillar inet-ip

### ISSUE THREAD

**Issue by ysicing** [goodrain/rainbond-install#45]
废弃inet-ip 配置，使用manage ip
```
# old
inet-ip: 172.16.0.1
# new
manage:
    members:
    - host: 172.16.0.1
      name: manage01
    - host: 172.16.0.2
      name: manage02
    - host: 172.16.0.3
      name: manage03
```
